---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-telegram-secret
  namespace: monitoring
spec:
  encryptedData:
    TELEGRAM_BOT_TOKEN: AgBQTSdJqMegIq2qMHlL1r2+KzBrvrzZktpcYP9MyGctKetLFdMQeRCKoCUAO8tFdhmyWi4Z0f3n1n17mqtZkMDg49c2RfqvUPU8b7cUo6GFizMXEPOlqlO3aLYqz37o+xDRHHwDyRGZOuIlu6jgX2YPiBtkyDNGWNvWWNVd4MVH/V7jh1SmSjW+bn8r/JKQ2c+CQ66Jz1CYcnelzUVw9loM6BQVdbTukjP+hHLcTwCq+oKFnCoqztW/PE1t6eeUmUr/srytCNQYH5Vi0xgNA9ryIrzrskteRD808P1RT8Lk8fX2f5RRS7IscOz3jHgkO/7H99R6nJHgeUhT/inIrIyCWZKOQCreYZniOwlvIDWdXbn9ip+HL9kqmqUAQFede1g6qSNQH3ZA3nTrXRT4XV5pd3UpxOosixsbKQ8e6qaVcq/8pEop2XaCi+uf2kiCkIm3QAscVwoLcYJkpOGL9ObXzUN0tZHuFx0wxsx8lzviOcyiTa7rV9yv3Dk02nLw1tZEgUhoOOp2aJZc5nV7c4fvQetBlbUS/Po/0rNKwtqHLr26IpJntSbNtTf5gRmS9tn9urYfHrGme2eVYxvzRXkFC3irhhyov+8h8nzvRZ/dOMZNE971212aXOZqYhOAZcPqs9eqrcTgF3UFMUhhKfwnrgmbu/oMNmWOqZONkVvrfUFOukVnElzpKutqMiYu1vt/C/wuGDDCxp3wu/ZlcfzZfQlPDYyd4cNo++UTP0s4ik5/cXsjAD2PJkwbPRaQ
    TELEGRAM_CHAT_ID: AgBB1tSR7jGiWljjJYK9+HvSHKmO0D5v+IlsvN51jl3cMWD/r05Go10dqdRDrm10bSS2SBiECqlT7YxsgG55KWwNhvOB26eNTCmPmSfSADVxtgnA7cxbEJBj6uynPF8HQ2K7AiiEEe7OrlRVCpQP0f3WRgBKLCKK8z3jXO4u4yW5SJx9iEyv/gSmaG4ylLKbkx8mc/iD6GKoJi5IDQXLrRgq1fr2yxmx6o9CGPzU6kkA99fJe3dJIGTFgnJ4j+BsyIR/8U6IM23R8WFpbJH/Dl6+2UHc3/Fd197JPnlgBM4J0GeobRM902kxWhyDrGdzke0GtNd1tGpZ+VNg3+0tK7zKB/lJAww28zzGf1vP9u/1/nYlAMv3twSkT6e+Adin21pSvJUefnuyq0F0l5HEo386zzKTqXswbPz5VettXC5L5FylytwVUTMuN3KPyw+MGJkX51iiMiDMF0u2dKVyAXlSFHmRTeu+BUDAzUmtjBYJi2+V20tg2tVg7IJHvdQlhjyKbfKmnazXMEnVOBMzjLr3LWRKQSlg7Q4vzKi7Sm/NsQh8ilWzXGpI0f+nlot+eZHoOcxoHgMybB3Bfue2pMUTHvaH+3f4oLvwpF0fZDj0CfQPVS8AwHYHkZBLcmM/8RHEF/xT+yG/wY0WdW9rT8mCkcXKeFEsaOJPwFUqw6KpXrvk6zGaWm2Li7l1PUGKLhHfnBi6aauxMdM+
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-telegram-secret
      namespace: monitoring
