---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: k8sgpt-opencodego
  namespace: monitoring
spec:
  encryptedData:
    openai-api-key: AgB3B8CV9YGDFSBaXTG5l2i+3f/VjPOwJ3a+jnq/Fa7aeinKFfEeb7E2jW+oieP3KkcNvLW8LfRKUBIh6FgX+D9Lq6uHi8IJqF7eXKdtIDMjHkeiCnZAPyibFc18jGp6caEfQ3s9nXd8+oKOlsyrB+O9vvorvj4GhFSp+JIsYsZBG8TKw7EiATPPSnkHP18NkEVcp96nT1gdaiqOwl5lK82vQnwxN6ocVzGKZg/wDRdl4PQG2xzvoWA/yO1RnL5ESNfucdkmSXI4M6ZVe5bxsB9IT9XvcWTh/95G/B+QriuC3xQePJtUhlxnHdamQ6zenZX2TmA+CqjAv5MJhHWmrK5sn8xkWfIR1Qit/EtZao8TrMf4iQxgPTcxusBBFZjuvVKT5NC5HxnSdePovzoPgWfMoxlQ81LJCgBoac23+8wPEkV5RtoFPrNksnC0CJTBgAqDOmEWQT1UzxhW5MsTZtsWSCMDyH6/NchPcuqjKO+33ilSxj/HsZUdcD9xSBo7l/CHQep3GexTvHvuri/O4CKrwrG2F8Cm9FkiVU4z7g6vkG6TJNoXeHgUq25IURtpKSp5YovfyNxOR4yiAIlt4GnlukXRGaJ/igaiEQrrbi9xgANiM3uRtyjpxoZ4jr0DGAde0Cwpty7j9B5NSWIdemIPze39SpGnfNot+btVqiFVbWNrMihaNpcNiCuBA0QF23IC2y2xEZ4cbXm4/ZS4UzMYK87U6W+qmoUSUxGbcImX72elqUVOoKC8JkosEV+mJYeVakbUE3Qypl/6gp9ElQRxTEbU
  template:
    metadata:
      creationTimestamp: null
      name: k8sgpt-opencodego
      namespace: monitoring
