{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "home-assistant.fullname" . }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "home-assistant.name" . }}
  endpoints:
    - port: http
      interval: {{ .Values.serviceMonitor.interval }}
      path: /api/prometheus
{{- end }}
